/** @type {import('tailwindcss').Config} */
// Root Tailwind config — wires Subframe-generated theme tokens
// into the Tailwind v4 pipeline via `@config` in globals.css.
// ui/subframe/tailwind.config.js is generated by `npm run subframe:sync`.
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./ui/**/*.{ts,tsx}",
  ],
  presets: [require("./ui/subframe/tailwind.config")],
};
