import type { ScoredItem, Cluster, FetchResult } from "./types.js";

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" });
  } catch {
    return iso;
  }
}

function scoreBar(score: number): string {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled) + ` ${score}`;
}

// =========================================================
// メインレポート (Markdown)
// =========================================================
export function renderReport(
  date: string,
  clusters: Cluster[],
  fetchResults: FetchResult[],
  totalFetched: number
): string {
  const warnings = fetchResults.filter((r) => r.error);
  const successCount = fetchResults.filter((r) => !r.error).length;

  const lines: string[] = [
    `# Market Pulse — ${date}`,
    "",
    `> Generated at ${new Date().toISOString()}`,
    `> Sources: ${successCount}/${fetchResults.length} OK${warnings.length ? ` / ${warnings.length} warnings` : ""}`,
    `> Total items fetched: ${totalFetched}`,
    "",
    "---",
    "",
    "## Top Clusters",
    "",
  ];

  // クラスタをtopScore降順で表示
  const sortedClusters = [...clusters].sort((a, b) => b.topScore - a.topScore);

  for (const [ci, cluster] of sortedClusters.slice(0, 10).entries()) {
    lines.push(`### ${ci + 1}. ${cluster.label} (top score: ${cluster.topScore})`);
    lines.push("");

    for (const item of cluster.items.slice(0, 5)) {
      lines.push(`#### [${item.title}](${item.url})`);
      lines.push(`- **Source**: ${item.sourceName} | **Published**: ${formatDate(item.publishedAt)}`);
      lines.push(`- **Score**: ${scoreBar(item.score.total)}`);
      lines.push(`  - Pain: ${item.score.pain} / Demand: ${item.score.demand} / Urgency: ${item.score.urgency}`);
      if (item.score.matchedKeywords.length > 0) {
        lines.push(`  - Keywords: \`${item.score.matchedKeywords.slice(0, 8).join("`, `")}\``);
      }
      if (item.summary.bullets.length > 0) {
        lines.push("- **Summary**:");
        for (const b of item.summary.bullets) {
          lines.push(`  - ${b}`);
        }
      }
      lines.push("");
    }

    if (cluster.items.length > 5) {
      lines.push(`<details><summary>+${cluster.items.length - 5} more items</summary>`);
      lines.push("");
      for (const item of cluster.items.slice(5)) {
        lines.push(`- [${item.title}](${item.url}) (score: ${item.score.total})`);
      }
      lines.push("</details>");
      lines.push("");
    }
  }

  // Warnings
  if (warnings.length > 0) {
    lines.push("---", "", "## Warnings", "");
    for (const w of warnings) {
      lines.push(`- ⚠️ \`${w.sourceId}\`: ${w.error}`);
    }
    lines.push("");
  }

  // All top items
  lines.push("---", "", "## All Top Items (score ≥ 20)", "");
  const topItems = sortedClusters
    .flatMap((c) => c.items)
    .filter((it) => it.score.total >= 20)
    .sort((a, b) => b.score.total - a.score.total)
    .slice(0, 30);

  if (topItems.length === 0) {
    lines.push("_(no items scored ≥ 20 today)_", "");
  } else {
    lines.push("| Score | Title | Source |");
    lines.push("|------:|-------|--------|");
    for (const it of topItems) {
      const title = it.title.slice(0, 60).replace(/\|/g, "\\|");
      lines.push(`| ${it.score.total} | [${title}](${it.url}) | ${it.sourceName} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// =========================================================
// Issue草案 (個別Markdown)
// =========================================================
export function renderIssueDraft(item: ScoredItem, date: string): { slug: string; content: string } {
  const slug = item.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);

  const content = [
    `# Issue Draft: ${item.title}`,
    "",
    `> Auto-generated by Market Pulse on ${date}`,
    `> Score: ${item.score.total} | Source: ${item.sourceName}`,
    `> Original: ${item.url}`,
    "",
    "## 痛み / 課題",
    "",
    ...item.summary.bullets.map((b) => `- ${b}`),
    "",
    "## LP案 / 訴求ポイント",
    "",
    "- TODO: このペインに対応する価値提案を記述",
    "- TODO: SHINENのどの機能が解決できるか",
    "",
    "## 想定ユーザー",
    "",
    "- TODO: どんな人が困っているか（職種、状況）",
    "",
    "## 検証アイデア",
    "",
    "- [ ] LP A/Bテストでこのペインを訴求する",
    "- [ ] 類似スレッドを5件以上収集してパターン確認",
    "- [ ] ユーザーインタビュー1件実施",
    "",
    "## スコア詳細",
    "",
    `- Pain: ${item.score.pain}`,
    `- Demand: ${item.score.demand}`,
    `- Urgency: ${item.score.urgency}`,
    `- Keywords: ${item.score.matchedKeywords.join(", ") || "(none)"}`,
    "",
    "## 元データ",
    "",
    "```",
    `Title: ${item.title}`,
    `Source: ${item.source}`,
    `Published: ${item.publishedAt}`,
    `Tags: ${item.tags.join(", ")}`,
    "```",
    "",
  ].join("\n");

  return { slug, content };
}
